services:
 sqlserver:
  platform: linux/amd64
  image: "mcr.microsoft.com/mssql/server:2022-latest"
  environment:
    ACCEPT_EULA: "Y" 
    SA_PASSWORD: "pa55w0rd!"
    MSSQL_PID: "Express"
  ports:
    - "1433:1433"